AWS_ACCOUNT = 120364521891
PIPELINE_VERSION = "1.0.0"
GIT_COMMIT := $(shell git rev-parse HEAD 2>/dev/null | cut -c 1-7)
APP_NAME := $(shell docker run -i -v /tmp:/root/.m2/repository --rm -v ${PWD}:/app -w="/app/build" maven:3.6-jdk-8-alpine mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.artifactId -q -DforceStdout)
APP_VERSION := $(shell docker run -i -v /tmp:/root/.m2/repository --rm -v ${PWD}:/app -w="/app/build" maven:3.6-jdk-8-alpine mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT//g' | grep -v executing)
IMAGE_TAG := $(shell echo "${APP_VERSION}-${GIT_COMMIT}")
HELM_DIR=helm-chart
