apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ include "app.fullname" . }}"
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-admin-timeout: "600"
    nginx.ingress.kubernetes.io/send-timeout: "600"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
spec:
  rules:
  - host: {{ .Values.ingress.url }}
    http:
      paths:
      - path: /
        backend:
          serviceName: "{{ include "app.fullname" . }}"
          servicePort: {{ .Values.service.app.servicePort }}
  tls:
  - hosts:
    - {{ .Values.ingress.url }}
    secretName: {{.Values.ingress.tls_secret}}
